//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toolbox.Extension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toolbox.Extension.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add migration.
        /// </summary>
        public static string AddMigrationMenuItemTitle {
            get {
                return ResourceManager.GetString("AddMigrationMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButtonCaption {
            get {
                return ResourceManager.GetString("BackButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseButtonCaption {
            get {
                return ResourceManager.GetString("BrowseButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonCaption {
            get {
                return ResourceManager.GetString("CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Make sure the project builds fine and run this wizard again &gt;.
        /// </summary>
        public static string CantBuildProjectComboBoxItem {
            get {
                return ResourceManager.GetString("CantBuildProjectComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database context.
        /// </summary>
        public static string DatabaseContext {
            get {
                return ResourceManager.GetString("DatabaseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database context class name.
        /// </summary>
        public static string DatabaseContextClassName {
            get {
                return ResourceManager.GetString("DatabaseContextClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database context and models scaffolding.
        /// </summary>
        public static string DatabaseScaffoldingMenuItemTitle {
            get {
                return ResourceManager.GetString("DatabaseScaffoldingMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; There is no public DbContext found. Add it, build the project and run this wizard again &gt;.
        /// </summary>
        public static string DbContextNotFoundComboBoxItem {
            get {
                return ResourceManager.GetString("DbContextNotFoundComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not build the following project: {0}.
        /// </summary>
        public static string MessageCantBuildProject {
            get {
                return ResourceManager.GetString("MessageCantBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not connect to database.
        /// </summary>
        public static string MessageCantConnectToDatabase {
            get {
                return ResourceManager.GetString("MessageCantConnectToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not tables in database.
        /// </summary>
        public static string MessageNotTablesInDatabase {
            get {
                return ResourceManager.GetString("MessageNotTablesInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully connected.
        /// </summary>
        public static string MessageSuccessfullyConnectedToDataabse {
            get {
                return ResourceManager.GetString("MessageSuccessfullyConnectedToDataabse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration name.
        /// </summary>
        public static string MigrationName {
            get {
                return ResourceManager.GetString("MigrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration namespace.
        /// </summary>
        public static string MigrationNamespace {
            get {
                return ResourceManager.GetString("MigrationNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrations.
        /// </summary>
        public static string Migrations {
            get {
                return ResourceManager.GetString("Migrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft SQL Server.
        /// </summary>
        public static string MsSqlServer {
            get {
                return ResourceManager.GetString("MsSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace for entity classes and database context.
        /// </summary>
        public static string NamespaceForScaffolding {
            get {
                return ResourceManager.GetString("NamespaceForScaffolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextButtonCaption {
            get {
                return ResourceManager.GetString("NextButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonCaption {
            get {
                return ResourceManager.GetString("OkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output folder.
        /// </summary>
        public static string OutputFolder {
            get {
                return ResourceManager.GetString("OutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember connection.
        /// </summary>
        public static string RememberConnection {
            get {
                return ResourceManager.GetString("RememberConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script migration.
        /// </summary>
        public static string ScriptMigrationMenuItemTitle {
            get {
                return ResourceManager.GetString("ScriptMigrationMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Server Authentication.
        /// </summary>
        public static string SqlServerAuth {
            get {
                return ResourceManager.GetString("SqlServerAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection.
        /// </summary>
        public static string StepDatabaseConnection {
            get {
                return ResourceManager.GetString("StepDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output parameters.
        /// </summary>
        public static string StepOutputParams {
            get {
                return ResourceManager.GetString("StepOutputParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string StepTables {
            get {
                return ResourceManager.GetString("StepTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string TestConnectionButtonCaption {
            get {
                return ResourceManager.GetString("TestConnectionButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use data annotation attributes.
        /// </summary>
        public static string UseDataAnnotationAttributes {
            get {
                return ResourceManager.GetString("UseDataAnnotationAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use database names.
        /// </summary>
        public static string UseDatabaseNames {
            get {
                return ResourceManager.GetString("UseDatabaseNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Authentication.
        /// </summary>
        public static string WindowsAuth {
            get {
                return ResourceManager.GetString("WindowsAuth", resourceCulture);
            }
        }
    }
}
